@startuml

hide empty members

package "HelloWorldExample" <<Cloud>> {
    class Publisher
}

package "Integration Services" <<Rectangle>> {
    package "helloworld_to_file" <<Rectangle>> {
        class fastrtps_subscriber
        class file_writer
    }
}

package " " <<Database>> {
    class "output.txt" as output
}

Publisher -> fastrtps_subscriber
fastrtps_subscriber -> file_writer
output <- file_writer


@enduml